### ISSUE TITLE
Missing Import in v14

### ISSUE THREAD

**Issue by thejoe8495** [alyf-de/pdf_on_submit#32]
In v14 there is no function with create_new_folder, everytime the document is first submited there came an error. Sometime it works but like the code it cant work? At the moment all doctypes removed but the error persists.

Frappe:
https://github.com/frappe/frappe/blob/17f94ac9979c30d2e9c4a56489431147dfca6445/frappe/core/doctype/file/file.py#L31
PDF on Submit:
https://github.com/alyf-de/erpnext_pdf-on-submit/blob/59f4efc405086cb57562e08a096bb41e76c06ff5/pdf_on_submit/attach_pdf.py#L22

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1581, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 999, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 978, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 303, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 354, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1079, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 908, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1257, in composer
    hooks.append(frappe.get_attr(handler))
  File "apps/frappe/frappe/__init__.py", line 1571, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1319, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1050, in _gcd_import
  File "", line 1027, in _find_and_load
  File "", line 1006, in _find_and_load_unlocked
  File "", line 688, in _load_unlocked
  File "", line 883, in exec_module
  File "", line 241, in _call_with_frames_removed
  File "apps/pdf_on_submit/pdf_on_submit/attach_pdf.py", line 22, in 
    from frappe.core.doctype.file.file import create_new_folder
ImportError: cannot import name 'create_new_folder' from 'frappe.core.doctype.file.file' (apps/frappe/frappe/core/doctype/file/file.py)

**Comment by barredterra** [comment]
Thanks for reporting. This should be fixed with https://github.com/alyf-de/erpnext_pdf-on-submit/commit/5c87eb5a60271d0c21d7e1a5604ccbbbe68df1bb
