### ISSUE TITLE
Error on Submit

### ISSUE THREAD

**Issue by wojosc** [alyf-de/pdf_on_submit#36]
When submitting a document I get an error at the moment:

```
ModuleNotFoundError: No module named 'frappe.core.api'

```

The error is:
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1473, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 1020, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1009, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 312, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 366, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1090, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 943, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in composer
    hooks.append(frappe.get_attr(handler))
  File "apps/frappe/frappe/__init__.py", line 1463, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1205, in get_module
    return importlib.import_module(modulename)
  File "env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "apps/pdf_on_submit/pdf_on_submit/attach_pdf.py", line 22, in <module>
    from frappe.core.api.file import create_new_folder
ModuleNotFoundError: No module named 'frappe.core.api'
```

This was tried on a Quotation with the following settings
<img width="1159" alt="grafik" src="https://user-images.githubusercontent.com/22279621/233906036-4340eb46-4669-4c1b-bf03-7c3e7ac786fb.png">

ERPNext: v13.49.12 (version-13)
Frappe Framework: v13.53.2 (version-13)

![grafik](https://user-images.githubusercontent.com/22279621/233913866-904e9804-73f6-4d03-add4-6c21011cfa05.png)

**Comment by wojosc** [comment]
we where able to fix this. The branches had not synced correctly between local and remote. Some hick-up. Closing.
